name       : hugin
version    : 2016.0.0
release    : 2
source     :
    - http://heanet.dl.sourceforge.net/project/hugin/hugin/hugin-2016.0/hugin-2016.0.0.tar.bz2 : b030b05b248b583cf9a26817f5b350303e3ce2c8bc4b43d45f697fbdf55b65e6
license    : GPL-2.0
summary    : Hugin - Panorama photo stitcher
description: |
    With Hugin you can assemble a mosaic of photographs into a complete immersive panorama, stitch any series of overlapping pictures and much more.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(glew)
    - pkgconfig(lcms2)
    - pkgconfig(libpano13)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(OpenEXR)
    - pkgconfig(sqlite3)
    - pkgconfig(xi)
    - pkgconfig(xmu)
    - fftw-devel
    - freeglut-devel
    - libboost-devel
    - libjpeg-turbo-devel
    - swig
    - vigra-devel
    - wxwidgets-devel
setup      : |
    mkdir build && cd build
    %cmake ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
