name       : hugin
homepage   : http://hugin.sourceforge.net/
version    : 2019.0.0
release    : 22
source     :
    - https://vorboss.dl.sourceforge.net/project/hugin/hugin/hugin-2019.0/hugin-2019.0.0.tar.bz2 : f94717c5035b776a552163bac5815916e0662008fabefafd790fa54b352e22d1
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Hugin - Panorama photo stitcher
description: |
    With Hugin you can assemble a mosaic of photographs into a complete immersive panorama, stitch any series of overlapping pictures and much more.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(glew)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(libpano13)
    - pkgconfig(libpng)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(OpenEXR)
    - pkgconfig(sqlite3)
    - pkgconfig(xi)
    - pkgconfig(xmu)
    - libboost-devel
    - swig
    - vigra-devel
    - wxwidgets-devel
rundeps    :
    - enblend-enfuse
    - lensfun
    - perl-image-exiftool
setup      : |
    %patch -p1 < $pkgfiles/hugin-exiv2-0-27-1.patch
    %cmake_ninja -DUSE_GDKBACKEND_X11=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
