name       : hugin
homepage   : http://hugin.sourceforge.net/
version    : 2017.0.0
release    : 9
source     :
    - https://nchc.dl.sourceforge.net/project/hugin/hugin/hugin-2017.0/hugin-2017.0.0.tar.bz2 : 86646ea27f32b959d38e7d36270703214b1ae961e379dd64b14d027139cd4609
license    : GPL-2.0
component  : multimedia.graphics
summary    : Hugin - Panorama photo stitcher
description: |
    With Hugin you can assemble a mosaic of photographs into a complete immersive panorama, stitch any series of overlapping pictures and much more.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(glew)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(libpano13)
    - pkgconfig(libpng)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(OpenEXR)
    - pkgconfig(sqlite3)
    - pkgconfig(xi)
    - pkgconfig(xmu)
    - freeglut-devel
    - libboost-devel
    - swig
    - vigra-devel
    - wxwidgets-devel
rundeps    :
    - enblend-enfuse
    - lensfun
    - perl-image-exiftool
setup      : |
    mkdir build && cd build
    %cmake ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
