name       : hugin
homepage   : http://hugin.sourceforge.net/
version    : 2018.0.0
release    : 18
source     :
    - https://netcologne.dl.sourceforge.net/project/hugin/hugin/hugin-2018.0/hugin-2018.0.0.tar.bz2 : d3af0d066ac50e3bb243a175a64ecda136d87178419457e8822e11bcf0e565cb
license    : GPL-2.0-or-later
component  : multimedia.graphics
summary    : Hugin - Panorama photo stitcher
description: |
    With Hugin you can assemble a mosaic of photographs into a complete immersive panorama, stitch any series of overlapping pictures and much more.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(fftw3)
    - pkgconfig(freeglut)
    - pkgconfig(glew)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(libpano13)
    - pkgconfig(libpng)
    - pkgconfig(libssh)
    - pkgconfig(libtiff-4)
    - pkgconfig(OpenEXR)
    - pkgconfig(sqlite3)
    - pkgconfig(xi)
    - pkgconfig(xmu)
    - libboost-devel
    - swig
    - vigra-devel
    - wxwidgets-devel
rundeps    :
    - enblend-enfuse
    - lensfun
    - perl-image-exiftool
clang      : yes
setup      : |
    %patch -p1 < $pkgfiles/cmake.patch
    mkdir build && cd build
    %cmake .. -DUSE_GDKBACKEND_X11=ON
build      : |
    %make -C build
install    : |
    %make_install -C build
