name       : hugin
version    : 2015.0.0
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/hugin/hugin/hugin-2015.0/hugin-2015.0.0.tar.bz2 : 2cd93c110be95d439f9e68653f3738d059a26f5c28973f75475ef59cbaa2cbbd
license    : GPL-2.0
summary    : Hugin - Panorama photo stitcher
description: |
    With Hugin you can assemble a mosaic of photographs into a complete immersive panorama, stitch any series of overlapping pictures and much more.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(glew)
    - pkgconfig(libpano13)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(OpenEXR)
    - pkgconfig(sqlite3)
    - pkgconfig(xi)
    - pkgconfig(xmu)
    - fftw-devel
    - freeglut-devel
    - libboost-devel
    - libjpeg-turbo-devel
    - swig
    - vigra-devel
    - wxwidgets-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
